version: '2'
services:
  shinobi:
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
      - ./videos:/opt/shinobi/videos
      - ./datadir:/var/lib/mysql
      - /dev/shm/shinobiDockerTemp:/dev/shm/streams
    ports:
      - "8080:8080"